---

- name: install essentials (workstation)
  become: yes
  become_method: doas
  when: ansible_os_family == "OpenBSD"
  openbsd_pkg:
    name: "{{item}}"
    state: present
  with_items:
    - ImageMagick
    - ansible
    - asciinema
    - bzip2
    - chromium
    - cmus
    - curl
    - djview4
    - exfat-fuse
    - exiftran
    - fdupes
    - feh
    - firefox
    - fswebcam
    - fzy
    - geeqie
    - ghostscript
    - gimp
    - gnome-themes-standard
    - gnuplot--no_x11
    - grap
    - graphviz
    - groff
    - heirloom-doctools
    - inkscape
    - ispell--russian
    - isync
    - jpegoptim
    - jhead
    - jq
    - jo
    - liberation-fonts
    - libqrencode
    - libreoffice
    - libreoffice-i18n-ru
    - lifelines
    - lowdown
    - maim
    - mc
    - moka-icon-theme
    - mpv
    - msmtp
    - mutt
    - noice
    - ntfs_3g
    - nvi--iconv
    - nnn
    - optipng
    - p5-Image-ExifTool
    - p7zip
    - p7zip-rar
    - passwdqc
    - pdfpc
    - pdfsandwich
    - pdftk
    - pianobar
    - pidgin--gtkspell
    - pjsua
    - pngcrush
    - py-casttube
    - remmina
    - restic
    - rofi
    - rtl-sdr
    - scrot
    - sxiv
    - sysclean
    - swish-e
    - tango-icon-theme
    - tango-icon-theme-extras
    - tarsnap-gui
    - tesseract
    - tesseract-rus
    - texlive_base
    - texlive_texmf-buildset
    - texlive_texmf-minimal
    - thunar
    - tor
    - unpaper
    - unzip
    - urlview
    - vim
    - xbattbar
    - xbindkeys
    - xcalib
    - xclip
    - xsel
    - xz
    - zathura
    - zathura-djvu
    - zathura-pdf-poppler
    - zathura-ps

- name: create directories
  become: no
  file:
    path: "{{item}}"
    state: "directory"
    owner: '{{ansible_user_id}}'
  with_items:
    - "{{ansible_env.HOME}}/sources/"
    - "{{ansible_env.HOME}}/bin/"

- name: install python
  become: yes
  become_method: doas
  when: ansible_os_family == "OpenBSD"
  openbsd_pkg:
    name: "{{item}}"
    state: latest
  with_items:
    - py-virtualenv
    - py-pip

- name: install various development packages
  become: yes
  become_method: doas
  when: ansible_os_family == "OpenBSD"
  openbsd_pkg:
    name: "{{item}}"
    state: latest
  with_items:
    - autoconf
    - automake
    - afl
    - cbmc
    - cmake
    - coq
    - entr
    - frama-c
    - gcc
    - git
    - gmake
    - go
    - jupyter-notebook
    - spin
    - mscgen
    - tkdiff
    - the_silver_searcher
    - z3

- name: install various games
  when: ansible_distribution == "OpenBSD"
  become: true
  become_method: doas
  openbsd_pkg:
    name: "{{item}}"
    state: present
  with_items:
    - chessx
    - openttd
    - xmahjongg
