---

# https://www.privacytools.io/
# Firefox configuration hardening https://github.com/pyllyukko/user.js
# https://firefox-source-docs.mozilla.org/mozbase/
# https://github.com/MozillaSecurity/ffpuppet
# https://marionette-client.readthedocs.io/en/master/
# https://firefox-puppeteer.readthedocs.io/en/master/
# https://github.com/mozilla/ff-tool
# Firefox: https://github.com/alzadude/ansible-firefox-addon
# Chromium: https://github.com/cmprescott/ansible-role-chrome

- name: ensure package firefox is installed
  when: ansible_os_family == "OpenBSD"
  openbsd_pkg:
    name: firefox
    state: present

- name: set firefox as default browser
  command: firefox -setDefaultBrowserSection

- name: set default search engine (TODO)
  command: echo

- name: ensure download directory exists
  file:
    dest: "/tmp/"
    state: directory
    mode: "0700"

# privacy.resistFingerprinting = true
# privacy.trackingprotection.enabled = true
# browser.cache.offline.enable = false
# browser.safebrowsing.malware.enabled = false
# browser.safebrowsing.phishing.enabled = false
# browser.send_pings = false
# ??? browser.sessionstore.max_tabs_undo = 0
# browser.urlbar.speculativeConnect.enabled = false
# dom.battery.enabled = false
# dom.event.clipboardevents.enabled = false
# geo.enabled = false
# media.navigator.enabled = false
# network.cookie.cookieBehavior = 1
# network.cookie.lifetimePolicy = 2
# network.http.referer.trimmingPolicy = 2
# network.http.referer.XOriginPolicy = 2
# network.http.referer.XOriginTrimmingPolicy = 2
# webgl.disabled = true
- name: setup about:config (TODO)
  command: echo

- name: ensure directory with certificates exists
  file:
    dest: "{{ansible_env.HOME}}/cert"
    state: directory

# https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Tools/certutil
# https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/tools/NSS_Tools_certutil
- name: install certificates in the the NSS database (TODO)
  command: certutil -addstore "Root" "{{ansible_env.HOME}}/cert/{{item}}"
  with_fileglob:
    - "{{ansible_env.HOME}}/cert/*"
