---

- name: install essentials (storage)
  become: yes
  become_method: doas
  when: ansible_os_family == "OpenBSD"
  openbsd_pkg:
    name: "{{item}}"
    state: present
  with_items:
    - cgit
    - curl
    - dkimproxy
    - dovecot
    - git
    - gitea
    - goaccess
    - mailpile
    - noice
    - restic
    - rss2email
    - rspamd
    - ttyd
    - sysclean
    - wireguard-go
    - wireguard-tools
