---

- name: trace become_method
  when: become_method is defined
  debug:
    var: become_method

- name: bootstrap
  import_tasks: bootstrap.yml

- name: install essentials
  import_tasks: install_essentials.yml

- name: install firmwares
  import_tasks: install_firmwares.yml

- name: setup system
  import_tasks: setup_system.yml

- name: setup services
  import_tasks: setup_services.yml

- name: configure user's crontab
  import_tasks: user_cron.yml

- name: configure cgit
  import_tasks: setup_cgit.yml
